<?php
$section=array();
$sectionName=array();
$topics=array();
$tags=array();
$page=array();
$slideRoot='img';
$slideExt='.png';

$slide[0]='Welcome '; $slideName[0]='Welcome'; $slidePage['Welcome']='0'; $slideTags[0]='welcome home'; $slideTopics[0]='';
$slide[1]='Functional'; $slideName[1]='Functional '; $slidePage['Functional1']='1'; $slideTags[1]='functional'; $slideTopics[1]='Ticket Activity Milestone Action Planning Workload Cost Report';
$slide[2]='Functional'; $slideName[2]='Functional (2)'; $slidePage['Functional2']='2'; $slideTags[2]='functional'; $slideTopics[2]='Expense Bill Risk Action Issue Meeting Decision Question Message Import ';
$slide[3]='Functional'; $slideName[3]='Functional (3)'; $slidePage['Functional3']='3'; $slideTags[3]='functional'; $slideTopics[3]='Client User Resource AccessRight Calendar';
$slide[4]='Functional'; $slideName[4]='Functional (4)'; $slidePage['Functional4']='4'; $slideTags[4]='functional'; $slideTopics[4]='Document Requirement Test Parameter';
$slide[5]='Functional'; $slideName[5]='Functional (5)'; $slidePage['Functional5']='5'; $slideTags[5]='functional'; $slideTopics[5]='AccessProfile GuiFilter';
$slide[6]='Technical'; $slideName[6]='Technical'; $slidePage['Technical1']='6'; $slideTags[6]='technical gui interface ajax browser'; $slideTopics[6]='GuiGenerality';
$slide[7]='Technical'; $slideName[7]='Technical (2)'; $slidePage['Technical2']='7'; $slideTags[7]='install setup deploy'; $slideTopics[7]='Installation';
$slide[8]='Technical'; $slideName[8]='Technical (3)'; $slidePage['Technical3']='8'; $slideTags[8]='parameter'; $slideTopics[8]='Parameters1';
$slide[9]='Installation'; $slideName[9]='Installation'; $slidePage['Installation']='9'; $slideTags[9]='install setup deploy php mysql http server zip'; $slideTopics[9]='Configuration Parameters1 NewVersion Connection';
$slide[10]='Configuration'; $slideName[10]='Configuration'; $slidePage['Configuration']='10'; $slideTags[10]='install setup config parameter'; $slideTopics[10]='Installation Parameters1 NewVersion Connection';
$slide[11]='Parameters'; $slideName[11]='Parameters'; $slidePage['Parameters1']='11'; $slideTags[11]='config parameter install setup'; $slideTopics[11]='Installation Configuration NewVersion';
$slide[12]='Parameters'; $slideName[12]='Parameters (2)'; $slidePage['Parameters2']='12'; $slideTags[12]='config parameter install setup'; $slideTopics[12]='Installation Configuration NewVersion';
$slide[13]='Parameters'; $slideName[13]='Parameters (3)'; $slidePage['Parameters3']='13'; $slideTags[13]='config parameter install setup'; $slideTopics[13]='Installation Configuration NewVersion';
$slide[14]='Parameters'; $slideName[14]='Parameters (4)'; $slidePage['Parameters4']='14'; $slideTags[14]='config parameter install setup'; $slideTopics[14]='Installation Configuration NewVersion';
$slide[15]='Parameters'; $slideName[15]='Parameters (5)'; $slidePage['Parameters5']='15'; $slideTags[15]='config parameter install setup'; $slideTopics[15]='Installation Configuration NewVersion';
$slide[16]='NewVersion'; $slideName[16]='Install new version'; $slidePage['NewVersion']='16'; $slideTags[16]='install setup deploy php mysql http server zip new version release update'; $slideTopics[16]='Installation Configuration Parameters1';
$slide[17]='Connection'; $slideName[17]='Connection'; $slidePage['Connection']='17'; $slideTags[17]='connect login'; $slideTopics[17]='GuiGenerality Installation Configuration';
$slide[18]='GUI'; $slideName[18]='User interface'; $slidePage['GuiGenerality']='18'; $slideTags[18]='gui interface'; $slideTopics[18]='Themes GuiToolbar GuiMenu GuiQuickMenu GuiList GuiFilter GuiDetail GuiCombo GuiAlert GuiProject';
$slide[19]='GUI'; $slideName[19]='Toolbars'; $slidePage['GuiToolbar']='19'; $slideTags[19]='gui interface toolbar show hide switch help manual hyperlink logo external-shortcuts shortcuts'; $slideTopics[19]='Themes GuiGenerality GuiMenu GuiQuickMenu GuiList GuiFilter GuiDetail GuiCombo GuiAlert GuiProject';
$slide[20]='GUI'; $slideName[20]='Menu'; $slidePage['GuiMenu']='20'; $slideTags[20]='gui interface menu project combo'; $slideTopics[20]='Themes GuiGenerality GuiToolbar GuiQuickMenu GuiList GuiFilter GuiDetail GuiCombo GuiAlert GuiProject';
$slide[21]='GUI'; $slideName[21]='Quick Menu'; $slidePage['GuiQuickMenu']='21'; $slideTags[21]='gui interface menu project combo'; $slideTopics[21]='Themes GuiGenerality GuiToolbar GuiMenu GuiList GuiFilter GuiDetail GuiCombo GuiAlert GuiProject';
$slide[22]='GUI'; $slideName[22]='List'; $slidePage['GuiList']='22'; $slideTags[22]='gui interface list column'; $slideTopics[22]='Themes GuiGenerality GuiToolbar GuiMenu GuiQuickMenu GuiFilter GuiDetail GuiCombo GuiAlert GuiProject';
$slide[23]='GUI'; $slideName[23]='Filter'; $slidePage['GuiFilter']='23'; $slideTags[23]='gui interface filter complex'; $slideTopics[23]='Themes GuiGenerality GuiToolbar GuiMenu GuiQuickMenu GuiList GuiDetail GuiCombo GuiAlert GuiProject';
$slide[24]='GUI'; $slideName[24]='ListParameter'; $slidePage['GuiListParameters']='24'; $slideTags[24]='gui interface list order selection width'; $slideTopics[24]='Themes GuiGenerality GuiToolbar GuiMenu GuiQuickMenu GuiList GuiDetail GuiCombo GuiAlert GuiProject';
$slide[25]='GUI'; $slideName[25]='Detail'; $slidePage['GuiDetail']='25'; $slideTags[25]='gui interface detail item save print'; $slideTopics[25]='Themes GuiGenerality GuiToolbar GuiMenu GuiQuickMenu GuiList GuiFilter GuiCombo GuiAlert GuiProject';
$slide[26]='GUI'; $slideName[26]='Combo detail'; $slidePage['GuiCombo']='26'; $slideTags[26]='gui interface detail item save print combo list'; $slideTopics[26]='Themes GuiGenerality GuiToolbar GuiMenu GuiQuickMenu GuiList GuiFilter GuiDetail  GuiAlert GuiProject';
$slide[27]='GUI'; $slideName[27]='Alert'; $slidePage['GuiAlert']='27'; $slideTags[27]='gui interface detail item save print combo list alert info warning'; $slideTopics[27]='Themes GuiGenerality GuiToolbar GuiMenu GuiQuickMenu GuiList GuiFilter GuiDetail GuiCombo GuiProject';
$slide[28]='Themes'; $slideName[28]='Themes'; $slidePage['Themes']='28'; $slideTags[28]='theme color'; $slideTopics[28]='GuiGenerality ThemesTemplates';
$slide[29]='Themes'; $slideName[29]='Themes templates'; $slidePage['ThemesTemplates']='29'; $slideTags[29]='theme color example'; $slideTopics[29]='GuiGenerality Themes';
$slide[30]='Multilingual'; $slideName[30]='Multilingual'; $slidePage['Multilingual']='30'; $slideTags[30]='english french german translat multiling'; $slideTopics[30]='GuiGenerality Configuration Parameters1';
$slide[31]='Creation'; $slideName[31]='Creation'; $slidePage['Creation']='31'; $slideTags[31]='creation'; $slideTopics[31]='GuiGenerality Update Delete Copy';
$slide[32]='Update'; $slideName[32]='Update'; $slidePage['Update']='32'; $slideTags[32]='update'; $slideTopics[32]='GuiGenerality Creation Delete copy';
$slide[33]='Delete'; $slideName[33]='Delete'; $slidePage['Delete']='33'; $slideTags[33]='delete'; $slideTopics[33]='GuiGenerality Creation Update Copy';
$slide[34]='Copy'; $slideName[34]='Copy'; $slidePage['Copy']='34'; $slideTags[34]='copy'; $slideTopics[34]='GuiGenerality Creation Update Delete';
$slide[35]='MultipleUpdate'; $slideName[35]='Multiple Update'; $slidePage['MultipleUpdate']='35'; $slideTags[35]='multiple update several grouped'; $slideTopics[35]='GuiGenerality Update';
$slide[36]='Today'; $slideName[36]='Today'; $slidePage['Today']='36'; $slideTags[36]='today summary todo message'; $slideTopics[36]='Message Project Ticket Activity Milestone Risk Action Issue';
$slide[37]='Today'; $slideName[37]='Today parameters'; $slidePage['TodayParameters']='37'; $slideTags[37]='today summary todo message'; $slideTopics[37]='Message Project Ticket Activity Milestone Risk Action Issue Report';
$slide[38]='Project'; $slideName[38]='Project'; $slidePage['Project']='38'; $slideTags[38]='project planning sub-project'; $slideTopics[38]='ProjectFields ProjectProgress ProjectAffectation ProjectDependencies GuiGenerality Creation Update Delete Planning';
$slide[39]='Project'; $slideName[39]='Project fields'; $slidePage['ProjectFields']='39'; $slideTags[39]='project planning sub-project hyperlink external-shortcuts shortcuts'; $slideTopics[39]='Project ProjectAffectation ProjectProgress ProjectDependencies GuiGenerality Creation Update Delete Planning Affectation Customer';
$slide[40]='Project'; $slideName[40]='Project affectations and versions'; $slidePage['ProjectAffectation']='40'; $slideTags[40]='project planning affectation version'; $slideTopics[40]='Project ProjectFields ProjectProgress ProjectDependencies GuiGenerality Creation Update Delete Planning';
$slide[41]='Project'; $slideName[41]='Project progress'; $slidePage['ProjectProgress']='41'; $slideTags[41]='project planning'; $slideTopics[41]='Project ProjectFields ProjectDependencies GuiGenerality Creation Update Delete Planning';
$slide[42]='Project'; $slideName[42]='Project dependencies'; $slidePage['ProjectDependencies']='42'; $slideTags[42]='project planning'; $slideTopics[42]='Project ProjectFields ProjectProgress ProjectAffectation GuiGenerality Creation Update Delete Planning';
$slide[43]='Document'; $slideName[43]='Document'; $slidePage['Document']='43'; $slideTags[43]='document directory file'; $slideTopics[43]='DocumentFields DocumentVersions DocumentDirectory DocumentApprovers Product Project';
$slide[44]='Document'; $slideName[44]='Document fields'; $slidePage['DocumentFields']='44'; $slideTags[44]='document directory file'; $slideTopics[44]='Document DocumentVersions DocumentDirectory DocumentApprovers Product Project LinkedElements';
$slide[45]='Document'; $slideName[45]='Document versions'; $slidePage['DocumentVersions']='45'; $slideTags[45]='document directory file version'; $slideTopics[45]='Document DocumentFields DocumentDirectory DocumentApprovers Product Project';
$slide[46]='Document'; $slideName[46]='Document approvers'; $slidePage['DocumentApprovers']='46'; $slideTags[46]='document directory file version approvers approve'; $slideTopics[46]='Document DocumentFields DocumentDirectory DocumentVersion Product Project';
$slide[47]='Ticket'; $slideName[47]='Ticket'; $slidePage['Ticket']='47'; $slideTags[47]='ticket bug task track'; $slideTopics[47]='TicketFields TicketSimple GuiGenerality Creation Update Delete TicketType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[48]='Ticket'; $slideName[48]='Ticket fields'; $slidePage['TicketFields']='48'; $slideTags[48]='ticket bug task track'; $slideTopics[48]='Ticket TicketSimple GuiGenerality Creation Update Delete TicketType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[49]='Ticket'; $slideName[49]='Ticket fields'; $slidePage['TicketFields2']='49'; $slideTags[49]='ticket bug task track work timer'; $slideTopics[49]='Ticket TicketSimple GuiGenerality Creation Update Delete TicketType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory';
$slide[50]='TicketSimple'; $slideName[50]='Simple Ticket'; $slidePage['TicketSimple']='50'; $slideTags[50]='ticket bug task track simple'; $slideTopics[50]='TicketSimpleFields Ticket GuiGenerality Creation Update Delete TicketType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[51]='TicketSimple'; $slideName[51]='Simple Ticket fields'; $slidePage['TicketSimpleFields']='51'; $slideTags[51]='ticket bug task track simple'; $slideTopics[51]='TicketSimple Ticket GuiGenerality Creation Update Delete TicketType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[52]='TicketSimple'; $slideName[52]='Simple Ticket fields'; $slidePage['TicketSimpleFields2']='52'; $slideTags[52]='ticket bug task track simple'; $slideTopics[52]='TicketSimple Ticket GuiGenerality Creation Update Delete TicketType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory';
$slide[53]='Activity'; $slideName[53]='Activity'; $slidePage['Activity']='53'; $slideTags[53]='activity task planning'; $slideTopics[53]='ActivityFields ActivityAssignment ActivityProgress ActivityDependencies GuiGenerality Creation Update Delete ActivityType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory Planning';
$slide[54]='Activity'; $slideName[54]='Activity fields'; $slidePage['ActivityFields']='54'; $slideTags[54]='activity task planning'; $slideTopics[54]='Activity ActivityAssignement ActivityProgress ActivityDependencies GuiGenerality Creation Update Delete ActivityType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory Planning';
$slide[55]='Activity'; $slideName[55]='Activity assignment'; $slidePage['ActivityAssignement']='55'; $slideTags[55]='activity task planning assignment'; $slideTopics[55]='Activity ActivityFields ActivityProgress ActivityDependencies GuiGenerality Creation Update Delete ActivityType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory Planning';
$slide[56]='Activity'; $slideName[56]='Activity progress'; $slidePage['ActivityProgress']='56'; $slideTags[56]='activity task planning progress'; $slideTopics[56]='Activity ActivityFields ActivityAssignment ActivityDependencies GuiGenerality Creation Update Delete ActivityType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory Planning';
$slide[57]='Activity'; $slideName[57]='Activity dependency'; $slidePage['ActivityDependencies']='57'; $slideTags[57]='activity task planning'; $slideTopics[57]='Activity ActivityFields ActivityAssignment ActivityProgress GuiGenerality Creation Update Delete ActivityType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory Planning';
$slide[58]='Milestone'; $slideName[58]='Milestone'; $slidePage['Milestone']='58'; $slideTags[58]='milestone flag '; $slideTopics[58]='MilestoneFields MilestoneProgress MilestoneDependencies GuiGenerality Creation Update Delete MilestoneType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory Planning';
$slide[59]='Milestone'; $slideName[59]='Milestone fields'; $slidePage['MilestoneFields']='59'; $slideTags[59]='milestone flag '; $slideTopics[59]='Milestone MilestoneProgress MilestoneDependencies GuiGenerality Creation Update Delete MilestoneType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory Planning';
$slide[60]='Milestone'; $slideName[60]='Milestone progress'; $slidePage['MilestoneProgress']='60'; $slideTags[60]='milestone flag '; $slideTopics[60]='Milestone MilestoneFields MilestoneDependencies GuiGenerality Creation Update Delete MilestoneType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory Planning';
$slide[61]='Milestone'; $slideName[61]='Milestone dependencies'; $slidePage['MilestoneDependencies']='61'; $slideTags[61]='milestone flag '; $slideTopics[61]='Milestone MilestoneFields MilestoneProgress GuiGenerality Creation Update Delete MilestoneType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory Planning';
$slide[62]='Action'; $slideName[62]='Action'; $slidePage['Action']='62'; $slideTags[62]='risk action issue'; $slideTopics[62]='ActionFields ActionDependencies Risk Issue GuiGenerality Creation Update Delete ActionType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[63]='Action'; $slideName[63]='Action fields'; $slidePage['ActionFields']='63'; $slideTags[63]='risk action issue'; $slideTopics[63]='Action ActionDependencies Risk Issue GuiGenerality Creation Update Delete ActionType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory';
$slide[64]='Action'; $slideName[64]='Action dependencies'; $slidePage['ActionDependencies']='64'; $slideTags[64]='risk action issue'; $slideTopics[64]='Action ActionFields Risk Issue GuiGenerality Creation Update Delete ActionType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[65]='Imputation'; $slideName[65]='Real work allocation'; $slidePage['Imputation']='65'; $slideTags[65]='imputation work follow-up allocation'; $slideTopics[65]='Activity ActivityAssignement Planning Resource Project Affectation';
$slide[66]='Planning'; $slideName[66]='Planning'; $slidePage['Planning1']='66'; $slideTags[66]='planning work plan date calculation gantt'; $slideTopics[66]='ActivityAssignement ActivityProgress ActivityDependencies';
$slide[67]='Planning'; $slideName[67]='Planning (2)'; $slidePage['Planning2']='67'; $slideTags[67]='planning work plan date calculation gantt'; $slideTopics[67]='ActivityAssignement ActivityProgress ActivityDependencies';
$slide[68]='Planning'; $slideName[68]='Planning (3)'; $slidePage['Planning3']='68'; $slideTags[68]='planning work plan date calculation gantt'; $slideTopics[68]='ActivityAssignement ActivityProgress ActivityDependencies';
$slide[69]='Planning'; $slideName[69]='Planning (4)'; $slidePage['Planning4']='69'; $slideTags[69]='planning work plan date calculation gantt'; $slideTopics[69]='ActivityAssignement ActivityProgress ActivityDependencies';
$slide[70]='Planning'; $slideName[70]='Planning (5)'; $slidePage['Planning5']='70'; $slideTags[70]='planning work plan date calculation gantt'; $slideTopics[70]='ActivityAssignement ActivityProgress ActivityDependencies';
$slide[71]='PortfolioPlanning'; $slideName[71]='Projects portfolio'; $slidePage['PortfolioPlanning']='71'; $slideTags[71]='planning gantt portfolio'; $slideTopics[71]='Planning';
$slide[72]='ResourcePlanning'; $slideName[72]='Resource Planning'; $slidePage['ResourcePlanning']='72'; $slideTags[72]='planning work plan date calculation gantt resource'; $slideTopics[72]='ActivityAssignement ActivityProgress ActivityDependencies Planning';
$slide[73]='Report'; $slideName[73]='Report'; $slidePage['Report']='73'; $slideTags[73]='parameter report print '; $slideTopics[73]='';
$slide[74]='Requirement'; $slideName[74]='Requirement'; $slidePage['Requirement']='74'; $slideTags[74]='requirement'; $slideTopics[74]='RequirementFields TestCase TestSession GuiGenerality Creation Update Delete RequirementType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[75]='Requirement'; $slideName[75]='Requirement fields'; $slidePage['RequirementFields']='75'; $slideTags[75]='requirement'; $slideTopics[75]='Requirement TestCase TestSession GuiGenerality Creation Update Delete RequirementType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[76]='Requirement'; $slideName[76]='Requirement fields'; $slidePage['RequirementFields2']='76'; $slideTags[76]='requirement'; $slideTopics[76]='Requirement TestCase TestSession GuiGenerality Creation Update Delete RequirementType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory';
$slide[77]='TestCase'; $slideName[77]='Test case'; $slidePage['TestCase']='77'; $slideTags[77]='test case'; $slideTopics[77]='TestCaseFields Requirement TestSession GuiGenerality Creation Update Delete TestCaseType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[78]='TestCase'; $slideName[78]='Test case fields'; $slidePage['TestCaseFields']='78'; $slideTags[78]='test case'; $slideTopics[78]='TestCase Requirement TestSession GuiGenerality Creation Update Delete TestCaseType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[79]='TestCase'; $slideName[79]='Test case fields'; $slidePage['TestCaseFields2']='79'; $slideTags[79]='test case'; $slideTopics[79]='TestCase Requirement TestSession GuiGenerality Creation Update Delete TestCaseType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[80]='TestSession'; $slideName[80]='Test session'; $slidePage['TestSession']='80'; $slideTags[80]='test session'; $slideTopics[80]='TestSessionFields Requirement TestCase GuiGenerality Creation Update Delete TestCaseType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[81]='TestSession'; $slideName[81]='Test session fields'; $slidePage['TestSessionFields']='81'; $slideTags[81]='test session'; $slideTopics[81]='TestSession Requirement TestCase GuiGenerality Creation Update Delete TestCaseType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[82]='TestSession'; $slideName[82]='Test session fields'; $slidePage['TestSessionFields2']='82'; $slideTags[82]='test session'; $slideTopics[82]='TestSession Requirement TestCase GuiGenerality Creation Update Delete TestCaseType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[83]='Command'; $slideName[83]='Order'; $slidePage['Command']='83'; $slideTags[83]='order bill command'; $slideTopics[83]='activity';
$slide[84]='Command'; $slideName[84]='Order fields'; $slidePage['CommandFields']='84'; $slideTags[84]='order bill command'; $slideTopics[84]='activity';
$slide[85]='IndividualExpense'; $slideName[85]='Individual expense'; $slidePage['IndividualExpense']='85'; $slideTags[85]='expense cost travel '; $slideTopics[85]='IndividualExpenseFields IndividualExpenseDetails ProjectExpense';
$slide[86]='IndividualExpense'; $slideName[86]='Individual expense fields'; $slidePage['IndividualExpenseFields']='86'; $slideTags[86]='expense cost travel '; $slideTopics[86]='IndividualExpense IndividualExpenseDetails ProjectExpense';
$slide[87]='IndividualExpense'; $slideName[87]='Individual expense details'; $slidePage['IndividualExpenseDetails']='87'; $slideTags[87]='expense cost travel detail'; $slideTopics[87]='IndividualExpenseFields IndividualExpense ProjectExpense';
$slide[88]='ProjectExpense'; $slideName[88]='Project expense'; $slidePage['ProjectExpense']='88'; $slideTags[88]='expense'; $slideTopics[88]='ProjectExpenseFields IndividualExpense';
$slide[89]='ProjectExpense'; $slideName[89]='Project expense fields'; $slidePage['ProjectExpenseFields']='89'; $slideTags[89]='expense'; $slideTopics[89]='ProjectExpense IndividualExpense';
$slide[90]='Term'; $slideName[90]='Term'; $slidePage['Term']='90'; $slideTags[90]='term trigger bill fixed price'; $slideTopics[90]='TermFileds Bill';
$slide[91]='Term'; $slideName[91]='Term fields'; $slidePage['TermFields']='91'; $slideTags[91]='term trigger bill fixed price'; $slideTopics[91]='Term Bill';
$slide[92]='Bill'; $slideName[92]='Bill'; $slidePage['Bill']='92'; $slideTags[92]='bill billing'; $slideTopics[92]='Term Bill ActivityPrice BillingType BillType';
$slide[93]='Bill'; $slideName[93]='Bill fields'; $slidePage['BillFields']='93'; $slideTags[93]='bill billing'; $slideTopics[93]='Term Bill ActivityPrice BillingType BillType Recipient Contact';
$slide[94]='Bill'; $slideName[94]='Bill lines'; $slidePage['BillLines']='94'; $slideTags[94]='risk action issue opportunity'; $slideTopics[94]='Term Bill ActivityPrice BillingType BillType';
$slide[95]='ActivityPrice'; $slideName[95]='Activity price'; $slidePage['ActivityPrice']='95'; $slideTags[95]='risk action issue opportunity'; $slideTopics[95]='Activity ActivityType BillingType';
$slide[96]='Risk'; $slideName[96]='Risk'; $slidePage['Risk']='96'; $slideTags[96]='risk action issue'; $slideTopics[96]='RiskFields Action Issue Opportunity GuiGenerality Creation Update Delete RiskType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[97]='Risk'; $slideName[97]='Risk fields'; $slidePage['RiskFields']='97'; $slideTags[97]='risk action issue'; $slideTopics[97]='Risk Action Issue Opportunity GuiGenerality Creation Update Delete RiskType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory';
$slide[98]='Opportunity'; $slideName[98]='Opportunity'; $slidePage['Opportunity']='98'; $slideTags[98]='meeting workshop steering committee invitation attendees'; $slideTopics[98]='OpportunityFields Risk Action Issue GuiGenerality Creation Update Delete RiskType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[99]='Opportunity'; $slideName[99]='Opportunity fields'; $slidePage['OpportunityFields']='99'; $slideTags[99]='meeting workshop steering committee'; $slideTopics[99]='Opportunity Risk Action Issue GuiGenerality Creation Update Delete RiskType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory';
$slide[100]='Issue'; $slideName[100]='Issue'; $slidePage['Issue']='100'; $slideTags[100]='risk action issue'; $slideTopics[100]='IssueFields IssueDependencies Risk Action GuiGenerality Creation Update Delete IssueType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[101]='Issue'; $slideName[101]='Issue fields'; $slidePage['IssueFields']='101'; $slideTags[101]='risk action issue'; $slideTopics[101]='Issue IssueDependencies Risk Action GuiGenerality Creation Update Delete IssueType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory';
$slide[102]='Meeting'; $slideName[102]='Meeting'; $slidePage['Meeting']='102'; $slideTags[102]='meeting workshop steering committee invitation attendees'; $slideTopics[102]='MeetingFields MeetingDependencies Question Decision GuiGenerality Creation Update Delete MeetingType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[103]='Meeting'; $slideName[103]='Meeting fields'; $slidePage['MeetingFields']='103'; $slideTags[103]='meeting workshop steering committee'; $slideTopics[103]='Meeting MeetingDependencies Question Decision GuiGenerality Creation Update Delete MeetingType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory';
$slide[104]='PeriodicMeeting'; $slideName[104]='Periodic meeting'; $slidePage['PeriodicMeeting']='104'; $slideTags[104]='meeting workshop steering committee invitation attendees periodic'; $slideTopics[104]='PeriodicMeetingFields Meeting MeetingType';
$slide[105]='PeriodicMeeting'; $slideName[105]='Periodic meeting fields'; $slidePage['PeriodicMeetingFields']='105'; $slideTags[105]='meeting workshop steering committee periodic'; $slideTopics[105]='PeriodicMeeting Meeting MeetingType';
$slide[106]='Decision'; $slideName[106]='Decision'; $slidePage['Decision']='106'; $slideTags[106]='decision'; $slideTopics[106]='DecisionFields DecisionDependencies Meeting GuiGenerality Creation Update Delete DecisionType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[107]='Decision'; $slideName[107]='Decision fields'; $slidePage['DecisionFields']='107'; $slideTags[107]='decision'; $slideTopics[107]='Decision DecisionDependencies Meeting GuiGenerality Creation Update Delete DecisionType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory';
$slide[108]='Question'; $slideName[108]='Question'; $slidePage['Question']='108'; $slideTags[108]='question answer'; $slideTopics[108]='QuestionFields QuestionDependencies Meeting GuiGenerality Creation Update Delete QuestionType Status AutomaticEmailing Workflow Attachments Notes ChangeHistory';
$slide[109]='Question'; $slideName[109]='Question fields'; $slidePage['QuestionFields']='109'; $slideTags[109]='question answer'; $slideTopics[109]='Question QuestionDependencies Meeting GuiGenerality Creation Update Delete QuestionType Status AutomaticEmailing Workflow LinkedElements Attachments Notes ChangeHistory';
$slide[110]='Mail'; $slideName[110]='Emails'; $slidePage['Mail']='110'; $slideTags[110]='email mail'; $slideTopics[110]='AutomaticEmailing';
$slide[111]='Alert'; $slideName[111]='Alerts'; $slidePage['Alert']='111'; $slideTags[111]='alert warning information indicator'; $slideTopics[111]='GuiAlert IndicatorDefinition';
$slide[112]='Message'; $slideName[112]='Message'; $slidePage['Message']='112'; $slideTags[112]='message alert'; $slideTopics[112]='User Project Profile Today';
$slide[113]='Import'; $slideName[113]='Import'; $slidePage['Import']='113'; $slideTags[113]='import load'; $slideTopics[113]='AutomaticImport Ticket Activity Milestone Risk Action Issue Meeting Decision Question Project Resource';
$slide[114]='Import'; $slideName[114]='Import Run'; $slidePage['ImportRun']='114'; $slideTags[114]='import load'; $slideTopics[114]='AutomaticImport Ticket Activity Milestone Risk Action Issue Meeting Decision Question Project Resource';
$slide[115]='AutomaticImport'; $slideName[115]='Automatic Import'; $slidePage['AutomaticImport']='115'; $slideTags[115]='automatic automated import cron'; $slideTopics[115]='Import GlobalParameter';
$slide[116]='Affectation'; $slideName[116]='Affectation'; $slidePage['Affectation']='116'; $slideTags[116]='affectation resource contact user project'; $slideTopics[116]='GuiGenerality Resource Contact User Project';
$slide[117]='User'; $slideName[117]='User'; $slidePage['User']='117'; $slideTags[117]='contact resource user login password'; $slideTopics[117]='GuiGenerality Contact Resource UserAffectation';
$slide[118]='User'; $slideName[118]='User affectations'; $slidePage['UserAffectation']='118'; $slideTags[118]='contact resource user login password affectation'; $slideTopics[118]='GuiGenerality Contact Resource User';
$slide[119]='Resource'; $slideName[119]='Resource description'; $slidePage['Resource']='119'; $slideTags[119]='resource capacity affectation'; $slideTopics[119]='ResourceCost GuiGenerality User Contact Team Planning Affectation';
$slide[120]='Resource'; $slideName[120]='Resource function cost & affectation'; $slidePage['ResourceCost']='120'; $slideTags[120]='resource capacity affectation cost'; $slideTopics[120]='GuiGenerality User Contact Team Planning Affectation Resource';
$slide[121]='Contact'; $slideName[121]='Contact'; $slidePage['Contact']='121'; $slideTags[121]='contact customer requestor'; $slideTopics[121]='Client User GuiGenerality Creation Update Delete AutomaticEmailing ContactAffectation';
$slide[122]='Contact'; $slideName[122]='Contact affectations'; $slidePage['ContactAffectation']='122'; $slideTags[122]='contact customer requestor affectation'; $slideTopics[122]='Client User GuiGenerality Creation Update Delete AutomaticEmailing Contact';
$slide[123]='Client'; $slideName[123]='Customer'; $slidePage['Client']='123'; $slideTags[123]='client customer contact'; $slideTopics[123]='Contact Project GuiGenerality Creation Update Delete';
$slide[124]='Recipient'; $slideName[124]='Recipient'; $slidePage['Recipient']='124'; $slideTags[124]='recipient bill'; $slideTopics[124]='Bill';
$slide[125]='Team'; $slideName[125]='Team'; $slidePage['Team']='125'; $slideTags[125]='team resource affectation'; $slideTopics[125]='GuiGenerality Resource';
$slide[126]='Product'; $slideName[126]='Product'; $slidePage['Product']='126'; $slideTags[126]='product version'; $slideTopics[126]='Version Project Customer Contact';
$slide[127]='Version'; $slideName[127]='Version'; $slidePage['Version']='127'; $slideTags[127]='product version'; $slideTopics[127]='Product Project Customer Contact';
$slide[128]='Context'; $slideName[128]='Context'; $slidePage['Context']='128'; $slideTags[128]='context environment os browser'; $slideTopics[128]='Ticket TranslatableName';
$slide[129]='Calendar'; $slideName[129]='Calendar'; $slidePage['Calendar']='129'; $slideTags[129]='calendar off open closed day'; $slideTopics[129]='GuiGenerality Planning';
$slide[130]='DocumentDirectory'; $slideName[130]='Document directory'; $slidePage['DocumentDirectory']='130'; $slideTags[130]='document directory folder place'; $slideTopics[130]='Document';
$slide[131]='Role'; $slideName[131]='Function'; $slidePage['Role']='131'; $slideTags[131]='function resource cost'; $slideTopics[131]='GuiGenerality Resource';
$slide[132]='Status'; $slideName[132]='Status'; $slidePage['Status']='132'; $slideTags[132]='status workflow lifecycle'; $slideTopics[132]='Workflow Ticket Activity Milestone Risk Action Issue Meeting Decision Question GuiGenerality';
$slide[133]='HealthStatus'; $slideName[133]='HealthStatus'; $slidePage['HealthStatus']='133'; $slideTags[133]='health'; $slideTopics[133]='Project Today';
$slide[134]='Likelihood'; $slideName[134]='Likelihood'; $slidePage['Likelihood']='134'; $slideTags[134]='likelihood probability'; $slideTopics[134]='GuiGenerality criticality severity risk';
$slide[135]='Criticality'; $slideName[135]='Criticality'; $slidePage['Criticality']='135'; $slideTags[135]='criticality'; $slideTopics[135]='GuiGenerality risk ticket likelihood severity priority urgency';
$slide[136]='Severity'; $slideName[136]='Severity'; $slidePage['Severity']='136'; $slideTags[136]='severity'; $slideTopics[136]='GuiGenerality risk criticality likelihood';
$slide[137]='Urgency'; $slideName[137]='Urgency'; $slidePage['Urgency']='137'; $slideTags[137]='urgency priority'; $slideTopics[137]='GuiGenerality ticket priority criticality';
$slide[138]='Priority'; $slideName[138]='Priority'; $slidePage['Priority']='138'; $slideTags[138]='priority urgency'; $slideTopics[138]='GuiGenerality urgency criticality ticket';
$slide[139]='RiskLevel'; $slideName[139]='Risk level'; $slidePage['RiskLevel']='139'; $slideTags[139]='risk level'; $slideTopics[139]='GuiGenerality';
$slide[140]='Feasibility'; $slideName[140]='Feasibility'; $slidePage['Feasibility']='140'; $slideTags[140]='feasibility'; $slideTopics[140]='GuiGenerality';
$slide[141]='Efficiency'; $slideName[141]='Efficiency'; $slidePage['Efficiency']='141'; $slideTags[141]='efficiency'; $slideTopics[141]='GuiGenerality Action';
$slide[142]='PredefinedNote'; $slideName[142]='Predefined note'; $slidePage['PredefinedNote']='142'; $slideTags[142]='predefined note text'; $slideTopics[142]='Notes';
$slide[143]='Workflow'; $slideName[143]='Workflow description'; $slidePage['Workflow']='143'; $slideTags[143]='workflow status'; $slideTopics[143]='Status Ticket Activity Milestone Risk Action Issue Meeting Decision Question GuiGenerality';
$slide[144]='Workflow'; $slideName[144]='Workflow table'; $slidePage['WorkflowTable']='144'; $slideTags[144]='workflow status'; $slideTopics[144]='Status Ticket Activity Milestone Risk Action Issue Meeting Decision Question GuiGenerality';
$slide[145]='StatusMail'; $slideName[145]='Mail on events'; $slidePage['StatusMail']='145'; $slideTags[145]='mail emailing status'; $slideTopics[145]='GuiGenerality Mail Status AutomaticEmailing ReplyToEmails';
$slide[146]='ReplyToEmail'; $slideName[146]='Reply to emails'; $slidePage['ReplyToEmail']='146'; $slideTags[146]='mail emailing reply'; $slideTopics[146]='GuiGenerality MailAutomaticEmailing';
$slide[147]='TicketDelay'; $slideName[147]='Delay for tickets'; $slidePage['TicketDelay']='147'; $slideTags[147]='delay ticket'; $slideTopics[147]='GuiGenerality Ticket';
$slide[148]='IndicatorDefinition'; $slideName[148]='Indicator'; $slidePage['IndicatorDefinition']='148'; $slideTags[148]='delay indicator alert warning'; $slideTopics[148]='Status Ticket Activity Milestone Risk Action Issue Meeting Decision Question GuiGenerality';
$slide[149]='ProjectType'; $slideName[149]='Project type'; $slidePage['ProjectType']='149'; $slideTags[149]='project type template administrative operational billing'; $slideTopics[149]='Project Bill';
$slide[150]='TicketType'; $slideName[150]='Ticket type'; $slidePage['TicketType']='150'; $slideTags[150]='type ticket'; $slideTopics[150]='Ticket GuiGenerality';
$slide[151]='ActivityType'; $slideName[151]='Activity type'; $slidePage['ActivityType']='151'; $slideTags[151]='activity type'; $slideTopics[151]='Activity GuiGenerality';
$slide[152]='MilestoneType'; $slideName[152]='Milestone type'; $slidePage['MilestoneType']='152'; $slideTags[152]='milestone type'; $slideTopics[152]='Milestone GuiGenerality';
$slide[153]='IndividualExpenseType'; $slideName[153]='Individual expense type'; $slidePage['IndividualExpenseType']='153'; $slideTags[153]='expense type'; $slideTopics[153]='IndividualExpense GuiGenerality';
$slide[154]='ProjectExpenseType'; $slideName[154]='Project expensetype'; $slidePage['ProjectExpenseType']='154'; $slideTags[154]='expense type'; $slideTopics[154]='ProjectExpense GuiGenerality';
$slide[155]='ExpenseDetailType'; $slideName[155]='Expense detail type'; $slidePage['ExpenseDetailType']='155'; $slideTags[155]='expense type'; $slideTopics[155]='IndividualExpense ProjectExpense GuiGenerality';
$slide[156]='BillType'; $slideName[156]='Bill type'; $slidePage['BillType']='156'; $slideTags[156]='bill type'; $slideTopics[156]='Bill GuiGenerality Creation Update Delete';
$slide[157]='RiskType'; $slideName[157]='Risk type'; $slidePage['RiskType']='157'; $slideTags[157]='risk type'; $slideTopics[157]='Risk GuiGenerality Creation Update Delete';
$slide[158]='RiskType'; $slideName[158]='Opportunity type'; $slidePage['Opportunity Type']='158'; $slideTags[158]='opportunity type'; $slideTopics[158]='Opportunity GuiGenerality Creation Update Delete';
$slide[159]='ActionType'; $slideName[159]='Action type'; $slidePage['ActionType']='159'; $slideTags[159]='action type'; $slideTopics[159]='Action GuiGenerality Creation Update Delete';
$slide[160]='IssueType'; $slideName[160]='Issue type'; $slidePage['IssueType']='160'; $slideTags[160]='issue type'; $slideTopics[160]='Issue GuiGenerality Creation Update Delete';
$slide[161]='MeetingType'; $slideName[161]='Meeting type'; $slidePage['MeetingType']='161'; $slideTags[161]='meeting type'; $slideTopics[161]='Meeting GuiGenerality Creation Update Delete';
$slide[162]='DecisionType'; $slideName[162]='Decision type'; $slidePage['DecisionType']='162'; $slideTags[162]='decision type'; $slideTopics[162]='Decision GuiGenerality Creation Update Delete';
$slide[163]='QuestionType'; $slideName[163]='Question type'; $slidePage['QuestionType']='163'; $slideTags[163]='question type'; $slideTopics[163]='Question GuiGenerality Creation Update Delete';
$slide[164]='MessageType'; $slideName[164]='Message type'; $slidePage['MessageType']='164'; $slideTags[164]='message type'; $slideTopics[164]='Message GuiGenerality Creation Update Delete';
$slide[165]='DocumentType'; $slideName[165]='Document type'; $slidePage['DocumentType']='165'; $slideTags[165]='document type'; $slideTopics[165]='Document GuiGenerality Creation Update Delete';
$slide[166]='ContextType'; $slideName[166]='Context type'; $slidePage['ContextType']='166'; $slideTags[166]='context type'; $slideTopics[166]='Context GuiGenerality Creation Update Delete';
$slide[167]='RequirementType'; $slideName[167]='Requirement type'; $slidePage['RequirementType']='167'; $slideTags[167]='requirement type'; $slideTopics[167]='Requirement GuiGenerality Creation Update Delete';
$slide[168]='TestCaseType'; $slideName[168]='Test case type'; $slidePage['TestCaseType']='168'; $slideTags[168]='test case type'; $slideTopics[168]='TestCase GuiGenerality Creation Update Delete';
$slide[169]='TestSessionType'; $slideName[169]='Test session type'; $slidePage['TestSessionType']='169'; $slideTags[169]='test session type'; $slideTopics[169]='TestSession GuiGenerality Creation Update Delete';
$slide[170]='Profile'; $slideName[170]='Profile'; $slidePage['Profile']='170'; $slideTags[170]='connection profile'; $slideTopics[170]='TranslatableName User';
$slide[171]='AccessProfile'; $slideName[171]='Access mode'; $slidePage['AccessProfile']='171'; $slideTags[171]='access mode read write update delete'; $slideTopics[171]='TranslatableName User Resource Profile';
$slide[172]='Habilitation'; $slideName[172]='Access to forms'; $slidePage['Habilitation']='172'; $slideTags[172]='ticket bug task track habilitation'; $slideTopics[172]='Profile AccessRight';
$slide[173]='HabilitationReport'; $slideName[173]='Access to reports'; $slidePage['HabilitationReport']='173'; $slideTags[173]='access report rights'; $slideTopics[173]='Profile';
$slide[174]='AccessRight'; $slideName[174]='Access mode to data'; $slidePage['AccessMode']='174'; $slideTags[174]='access screen form rights'; $slideTopics[174]='Profile Habilitation';
$slide[175]='HabilitationOther'; $slideName[175]='Specific access mode'; $slidePage['HabilitationOther']='175'; $slideTags[175]='access specific'; $slideTopics[175]='User Profile GuiCombo';
$slide[176]='HabilitationOther'; $slideName[176]='Specific access mode'; $slidePage['HabilitationOther2']='176'; $slideTags[176]='access specific'; $slideTopics[176]='User Profile GuiCombo';
$slide[177]='Administration'; $slideName[177]='Global parameters'; $slidePage['Administration']='177'; $slideTags[177]='administration cron maintenance purge'; $slideTopics[177]='';
$slide[178]='Audit'; $slideName[178]='Audit connections'; $slidePage['Audit']='178'; $slideTags[178]='connections who_is_online'; $slideTopics[178]='';
$slide[179]='GlobalParameter'; $slideName[179]='Global parameters'; $slidePage['GlobalParameter']='179'; $slideTags[179]='parameters ldap reference format'; $slideTopics[179]='';
$slide[180]='GlobalParameter'; $slideName[180]='Global parameters'; $slidePage['GlobalParameter2']='180'; $slideTags[180]='parameters ldap billing format'; $slideTopics[180]='';
$slide[181]='GlobalParameter'; $slideName[181]='Global parameters'; $slidePage['GlobalParameter3']='181'; $slideTags[181]='parameters ldap billing format'; $slideTopics[181]='';
$slide[182]='GlobalParameter'; $slideName[182]='Global parameters'; $slidePage['GlobalParameter4']='182'; $slideTags[182]='parameters ldap billing format'; $slideTopics[182]='';
$slide[183]='GlobalParameter'; $slideName[183]='Global parameters'; $slidePage['GlobalParameter5']='183'; $slideTags[183]='parameters ldap billing format'; $slideTopics[183]='';
$slide[184]='GlobalParameter'; $slideName[184]='Global parameters'; $slidePage['GlobalParameter6']='184'; $slideTags[184]='parameters ldap billing format'; $slideTopics[184]='';
$slide[185]='UserParameter'; $slideName[185]='User parameters'; $slidePage['UserParameter']='185'; $slideTags[185]='parameters'; $slideTopics[185]='';
$slide[186]='TranslatableName'; $slideName[186]='Translatable name'; $slidePage['translatableName']='186'; $slideTags[186]='translatable translation name profile'; $slideTopics[186]='AccessProfile ConnectionProfile';
$slide[187]='AutomaticEmailing'; $slideName[187]='Automatic emailing'; $slidePage['AutomaticEmailing']='187'; $slideTags[187]=''; $slideTopics[187]='Mail Status GuiGenerality Creation Update Delete';
$slide[188]='LinkedElements'; $slideName[188]='Linked elements'; $slidePage['LinkedElements']='188'; $slideTags[188]='link linked'; $slideTopics[188]='';
$slide[189]='Attachments'; $slideName[189]='Attachments'; $slidePage['Attachments']='189'; $slideTags[189]='attach file link privacy'; $slideTopics[189]='Ticket Activity Milestone Risk Issue Meeting Decision Question Parameters4 UserParameters';
$slide[190]='Notes'; $slideName[190]='Notes'; $slidePage['Notes']='190'; $slideTags[190]='note comment privacy predefined'; $slideTopics[190]='Ticket Activity Milestone Risk Action Issue Meeting Decision Question UserParameters';
$slide[191]='ChangeHistory'; $slideName[191]='Change history'; $slidePage['ChangeHistory']='191'; $slideTags[191]='change history track update'; $slideTopics[191]='UserParameters';
$slide[192]='Backup'; $slideName[192]='Backup / Restore'; $slidePage['Backup']='192'; $slideTags[192]='backup restore'; $slideTopics[192]='';
$slide[193]='Shortcuts'; $slideName[193]='Shortcuts'; $slidePage['Shortcuts']='193'; $slideTags[193]='shortcut key'; $slideTopics[193]='';
$slide[194]='LastWords'; $slideName[194]='Last words'; $slidePage['LastWords']='194'; $slideTags[194]='murphy hofstader history version'; $slideTopics[194]='';

if (! isset($includeManual)) {
  foreach ($slide as $id=>$name) {
    echo 'slide[' . $id . ']=' . $name . '<br/>';
  }
}

$prec='';
foreach ($slide as $id=>$name) {
  if (substr($name,0,2)=='X ') {
    unset($slide[$id]);
    unset($slideName[$id]);
    unset($slidePage[$id]);
    unset($slideTags[$id]);
    unset($slideTopics[$id]);
  } else {
    if ($name!=$prec) {
      $section[$id]=$name;
      $sectionName[$name]=$slideName[$id];
      $prec=$name;
    }
  }
}
$tags=array();
foreach ($slideTags as $id=>$name) {
 $split=explode(" ",$name);
 foreach ($split as $tag) {
   if (trim($tag) and !array_key_exists($tag, $tags)) {
     $tags[$tag]=array();
   }
   $tags[$tag][]=$id;
 }
}
ksort($tags);